version: "3.9"
services:
  websocket:
    build:
      context: ./cmd
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVICE_HOST=entry
    ports:
      - "2828:2828"
    networks:
      - backend
  entry:
    build:
      context: ./microservices/entry
      dockerfile: Dockerfile
    environment:
      - GRPC_USER_HOST=user
      - GRPC_ORDER_HOST=order
    ports:
      - "80:80"
    depends_on:
      - redis
    networks:
      - backend
  user:
    build:
      context: ./microservices/user
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    ports:
      - "81:81"
    depends_on:
      - redis
    networks:
      - backend
  order:
    build:
      context: ./microservices/order
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    ports:
      - "82:82"
    depends_on:
      - redis
    networks:
      - backend
  redis:
    image: "redis"
    restart: always
    networks:
      - backend
networks:
  backend: