version: "3.9"
services:
  websocket:
    build:
      context: ./cmd
      dockerfile: Dockerfile
    ports:
      - 2828:2828
    networks:
      - backend
  entry:
    build:
      context: ./microservices/entry
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - redis
    networks:
      - backend
  user:
    build:
      context: ./microservices/user
      dockerfile: Dockerfile
    ports:
      - 81:81
    depends_on:
      - redis
    networks:
      - backend
  order:
    build:
      context: ./microservices/order
      dockerfile: Dockerfile
    ports:
      - 82:82
    depends_on:
      - redis
    networks:
      - backend
  redis:
    image: "redis"
    restart: always
    networks:
      - backend
networks:
  backend: